name: "Snyk Code and Open Source Scan"
on: push

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Code Scan'
    runs-on: ubuntu-latest
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       
    steps:
    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v1

    # Install and Authenticate to Snyk
    - name: Install Snyk & Authenticate
      run: |
         sudo npm install -g snyk
         snyk auth ${SNYK_TOKEN}

    # Run Snyk Open Source 
    - name: Run Snyk Open Source
      run: |
         snyk test --unmanaged 
      continue-on-error: true

    # Run Snyk Open Source JSON format
    - name: Run Snyk Open Source
      run: |
         snyk test --unmanaged --json
      continue-on-error: true

    # Run Snyk Code
    - name: Run Snyk Code
      run: |
         snyk code test
      continue-on-error: true
      
    # Run Snyk Code SARIF Format
    - name: Run Snyk Code
      run: |
         snyk code test --sarif  > results.sarif
      continue-on-error: true
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: results.sarif


